name: my_flutter_unsplash_photo_gallery
description: "A new Flutter project."



version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  firebase_core: 2.24.2
  firebase_auth: ^4.16.0
  firebase_storage: ^11.6.0
  cloud_firestore: ^4.14.0
  json_annotation: ^4.8.1
  image_picker: ^1.0.7
  photo_view: ^0.14.0
  freezed_annotation: ^2.4.1
  http: ^1.1.0
  cupertino_icons: ^1.0.2
  redux: ^5.0.0
  flutter_redux: ^0.10.0
  redux_epics: ^0.15.1
  rxdart: ^0.27.7
  url_launcher: ^6.2.1
  multi_select_flutter: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^2.4.6
  flutter_lints: ^2.0.0

flutter:
  assets:
    - .env
  uses-material-design: true


