// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6AJNebsvw4C__tJBn5UObeImlDRtBnS4',
    appId: '1:446493970323:web:073abf195e44793477a266',
    messagingSenderId: '446493970323',
    projectId: 'unsplash-photo-gallery',
    authDomain: 'unsplash-photo-gallery.firebaseapp.com',
    storageBucket: 'unsplash-photo-gallery.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi1AyJFqLvo_316vp7aDmoZUKsRFMnLUQ',
    appId: '1:446493970323:android:50b9883eac7cf75677a266',
    messagingSenderId: '446493970323',
    projectId: 'unsplash-photo-gallery',
    storageBucket: 'unsplash-photo-gallery.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhVyYF5x71XPnKFWg0bDMO1CiXNASGcbY',
    appId: '1:446493970323:ios:e25982d1d013a96d77a266',
    messagingSenderId: '446493970323',
    projectId: 'unsplash-photo-gallery',
    storageBucket: 'unsplash-photo-gallery.appspot.com',
    iosBundleId: 'com.example.t6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhVyYF5x71XPnKFWg0bDMO1CiXNASGcbY',
    appId: '1:446493970323:ios:f7618badd2ade8dc77a266',
    messagingSenderId: '446493970323',
    projectId: 'unsplash-photo-gallery',
    storageBucket: 'unsplash-photo-gallery.appspot.com',
    iosBundleId: 'com.example.t6.RunnerTests',
  );
}
